defaults:
  - _self_
  - data: project
  - model: project
  - callbacks: null
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
  - optional local: default
  - debug: null

seed: 1234
ckpt_path: null
